### PR TITLE
Fixed Legend for Courses with One-Semester Data

### PR DESCRIPTION
**Pull request by kartik1000**
Now, legend will also be shown for courses which have only one semester data

### CODE REVIEW

**Comment by kartik1000** [comment]
Ok👍

**Comment by Ayushk4** [comment]
@kartik1000 next time onwards also mention the issue. This helps keeps track of issues that need to be closed.

**Comment by Ayushk4** [comment]
Refer #56

**Comment by kartik1000** [comment]
Ok

**Pull request merged**
