### PR TITLE
updated Kronos.html

### PR DESCRIPTION
**Pull request by kartik1000**
Removed Colours which matched Background Colour, also added few distinctive colours which were different and visible in presence of Background

### CODE REVIEW

**Comment by kartik1000** [comment]
Shall I commit The Bug Fix Error to some different branch? Do let me know whichever desired changes to be made:)

**Comment by Ayushk4** [comment]
I will get back to you on this by tomorrow morning latest. In case I don't, then ping me in the metakgp slack channel.

**Comment by Ayushk4** [comment]
Hey @kartik1000 . I appreciate this. Firstly, Thanks for fixing the DropDown Bug and for removing the repeated background colors. 

Couple of things I noted here.
This PR was sent by your master branch, this is not recommended. Instead you should create another branch and send a PR from that.

**Comment by Ayushk4** [comment]
Hey @kartik1000 . I appreciate this. Firstly, Thanks for fixing the DropDown Bug and for removing the repeated background colors. 

Couple of things I noted here.
This PR was sent by your master branch, this is not recommended. Instead you should create another branch and send a PR from that. 
Also, the color codes are not consistent with the rest. If you feel like, then please either make it all small letters and entirely capital letter.

**Comment by kartik1000** [comment]
Thanks, @Ayushk4 will make the required changes and let you know :)

**Comment by Ayushk4** [comment]
I am close this via #48

**Pull request closed without merging**
